// Writes src/environments/environment.mobile.ts from MOBILE_API_URL before a mobile build.
// The native app can't use the dev-server proxy, so the backend URL is compiled in.
//
//   MOBILE_API_URL=https://<codespace>-8080.app.github.dev/api npm run build:mobile
//
// Default: http://10.0.2.2:8080/api -- the host machine as seen from the Android emulator.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const apiUrl = (process.env.MOBILE_API_URL ?? 'http://10.0.2.2:8080/api').replace(/\/+$/, '');
if (!/^https?:\/\/[^/]+/.test(apiUrl)) {
  console.error(`MOBILE_API_URL must be an absolute http(s) URL, got "${apiUrl}"`);
  process.exit(1);
}

const target = fileURLToPath(new URL('../src/environments/environment.mobile.ts', import.meta.url));
writeFileSync(
  target,
  `// Generated by scripts/mobile-env.mjs -- do not edit, do not commit.
export const environment = {
  production: true,
  apiUrl: ${JSON.stringify(apiUrl)}
};
`
);
console.log(`Mobile API URL: ${apiUrl}`);
